name = "Cart Uplift - Working Version"
uid = "56116988-61a5-cf2b-23d1-e78f8a90260dc513e9d0"
type = "theme"
handle = "cart-drawer"

[settings]
  [[settings.fields]]
    key = "enable_cart_uplift"
    type = "checkbox"
    name = "Enable Cart Uplift"
    info = "Turn on Cart Uplift functionality. Configure detailed settings in your app admin."
    default = true

