#!/bin/bash

echo "🧹 Complete Cache Clear for Shopify Embedded App"
echo "================================================"
echo ""
echo "Follow these steps IN ORDER:"
echo ""

echo "1️⃣  Close ALL Shopify Admin tabs"
echo "   - Close every tab with admin.shopify.com"
echo "   - This ensures no cached iframes remain"
echo ""

echo "2️⃣  Clear browser cache (Chrome/Edge/Brave):"
echo "   - Press Cmd+Shift+Delete (Mac) or Ctrl+Shift+Delete (Windows)"
echo "   - Select 'Cached images and files'"
echo "   - Time range: 'Last hour' or 'All time'"
echo "   - Click 'Clear data'"
echo ""

echo "3️⃣  Alternative: Use Incognito/Private window"
echo "   - Cmd+Shift+N (Mac) or Ctrl+Shift+N (Windows)"
echo "   - Visit: https://admin.shopify.com/store/sectionappblocks/apps/cartuplift-2"
echo ""

echo "4️⃣  Wait for Vercel deployment (check status):"
echo "   https://vercel.com/adedayo14/cartuplift"
echo "   - Look for green ✓ on latest commit"
echo "   - Usually takes 60-90 seconds"
echo ""

echo "5️⃣  Open console BEFORE clicking button:"
echo "   - Press F12 or Cmd+Option+I"
echo "   - Go to Console tab"
echo "   - You should see: '🔍 CLIENT DEBUG v2: Dashboard loaded with:'"
echo "   - If you see 'v2', cache is cleared and new version loaded!"
echo ""

echo "6️⃣  Click 'Setup Revenue Tracking' button"
echo "   - Watch console for:"
echo "     🔧 Starting webhook setup..."
echo "     📡 Fetching: /admin/setup-webhooks?..."
echo "     📥 Response status: 200"
echo "     ✅ Response data: {...}"
echo ""

echo "7️⃣  If STILL seeing old version:"
echo "   - The iframe might be cached by Shopify"
echo "   - Try adding ?nocache=\$(date +%s) to URL"
echo "   - Or reinstall the app (uninstall then reinstall)"
echo ""

echo "🎯 Expected Success:"
echo "   - Console shows 'v2' in debug log"
echo "   - Button completes in ~2 seconds"
echo "   - Message shows '✓ Webhooks configured'"
echo "   - Webhook appears at: https://admin.shopify.com/store/sectionappblocks/settings/notifications/webhooks"
