import { saveSettings } from '../app/models/settings.server.ts';

const shop = 'sectionappblocks.myshopify.com';

const payload = {
  enableApp: true,
  showOnlyOnCartPage: false,
  autoOpenCart: true,
  enableFreeShipping: true,
  freeShippingThreshold: 150,
  enableRecommendations: true,
  enableAddons: false,
  enableDiscountCode: true,
  enableNotes: true,
  enableExpressCheckout: true,
  enableAnalytics: true,
  enableTitleCaps: false,
  enableRecommendationTitleCaps: true,
  cartIcon: 'cart',
  freeShippingText: "You're {amount} away from free shipping!",
  freeShippingAchievedText: "🎉 You've unlocked free shipping!",
  recommendationsTitle: 'You might also like',
  actionText: 'Add discount code',
  addButtonText: 'Add',
  checkoutButtonText: 'CHECKOUT',
  applyButtonText: 'Apply',
  discountLinkText: '+ Script test discount',
  notesLinkText: '+ Script test notes',
  backgroundColor: '#ffffff',
  textColor: '#1A1A1A',
  buttonColor: '#000000',
  buttonTextColor: '#ffffff',
  recommendationsBackgroundColor: '#ecebe3',
  shippingBarBackgroundColor: '#f0f0f0',
  shippingBarColor: '#121212',
  recommendationLayout: 'horizontal',
  maxRecommendations: 4,
  maxRecommendationProducts: 4,
  complementDetectionMode: 'automatic',
  manualRecommendationProducts: '',
  progressBarMode: 'free-shipping',
  enableGiftGating: false,
  giftProgressStyle: 'single-next',
  giftThresholds: '[]',
  giftThreshold: 150,
  giftNoticeText: 'Free gift added: {{product}} (worth {{amount}})',
  giftPriceText: 'FREE',
  mlPersonalizationMode: 'balanced',
  enableMLRecommendations: true,
  mlPrivacyLevel: 'basic',
  enableAdvancedPersonalization: true,
  enableBehaviorTracking: true,
  mlDataRetentionDays: '90',
};

console.log('Saving payload...');
const result = await saveSettings(shop, payload);
console.log('Save result:', {
  discountLinkText: result.discountLinkText,
  notesLinkText: result.notesLinkText,
  enableRecommendationTitleCaps: result.enableRecommendationTitleCaps,
});
