#!/bin/bash

echo ""
echo "🔍 WEBHOOK DIAGNOSTIC CHECKLIST"
echo "================================"
echo ""
echo "1️⃣  CHECK SHOPIFY WEBHOOK REGISTRATION"
echo "   → Go to: https://admin.shopify.com/store/sectionappblocks/settings/notifications"
echo "   → Look for: 'Webhooks' section"
echo "   → Verify: 'Order creation' webhook exists"
echo "   → Should point to: https://cartuplift.vercel.app/webhooks/orders/create"
echo ""
echo "2️⃣  CHECK VERCEL FUNCTION LOGS"
echo "   → Go to: https://vercel.com/adedayo14/cartuplift/logs"
echo "   → Filter by: '/webhooks/orders/create'"
echo "   → Look for: Recent webhook calls with '🎯 Order webhook START'"
echo ""
echo "3️⃣  MANUAL WEBHOOK TEST"
echo "   → In Shopify webhooks page, find 'Order creation' webhook"
echo "   → Click 'Send test notification'"
echo "   → Check Vercel logs for response"
echo ""
echo "4️⃣  CHECK PRODUCT ID FORMAT"
echo "   Your latest order had these products:"
echo "   - Hi top calf leather"
echo "   - The Letterman"
echo ""
echo "   → Go to Shopify Products page"
echo "   → Click on 'Hi top calf leather'"
echo "   → Check URL for product ID (e.g., /products/1234567890)"
echo "   → Compare with tracking event product IDs"
echo ""
echo "5️⃣  QUICK FIX: Re-deploy webhook"
echo "   Run: cd /Users/dayo/CartUpliftAI/CartUpliftAI && shopify app deploy"
echo "   This will re-register all webhooks"
echo ""
echo "📋 COMMON ISSUES:"
echo "   ❌ Webhook not registered → Run 'shopify app deploy'"
echo "   ❌ Product ID mismatch → Check if IDs include 'gid://shopify/Product/' prefix"
echo "   ❌ Webhook timing out → Check Vercel function logs for errors"
echo "   ❌ Database write failing → Check Neon Postgres connection"
echo ""
